### ISSUE TITLE
Converting net6

### ISSUE THREAD

**Issue by Hardshop18** [voxsoftware/jxshell.dotnet4#3]
I started converting the project to net6, but I'm having some problems using the dll. And put the project on pull requests.

**Comment by voxsoftware** [comment]
Hi, thanks for your collaboration. I created a new branch net6.0 
Please make PR to that branch. Also, please ensure to add .gitignore for debug folder, I don't want compiled files on repository.

I will accept the PR and start work on new branch  net6.0

**Comment by jader1313** [comment]
@voxsoftware can you check if the new PR by @Hardshop18  is ok?

**Comment by Hardshop18** [comment]
Hi @voxsoftware. 
Is the new PR that was created in line with what was requested?

**Comment by jader1313** [comment]
Can anyone help?

**Comment by voxsoftware** [comment]
I just merged. I will make tests and see if anything work as expected. Thanks for your collaboration.

**Comment by jader1313** [comment]
Can we help in any way to expedite the solution?

**Comment by voxsoftware** [comment]
You can check the branch net6.0 and see if work as expected.

**Comment by voxsoftware** [comment]
This project was replaced by a new project with better practices and faster code.
https://github.com/FoxShell/kodnetlib
